## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx    #build never started in travis CI, will trouble shoot later
julia:
  - 0.6
  - nightly
notifications:
  email: false
git:
  depth: 99999999
matrix:
  allow_failures:
  - osx: v0.6
  - osx: nightly
  - julia: nightly

addons:
  apt_packages:
    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
script:
  - julia -e 'Pkg.clone(pwd()); Pkg.build("EAGO"); Pkg.test("EAGO"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("EAGO")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'   # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("EAGO")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'       # push coverage results to Codecov
